theme: jekyll-theme-slate
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-github-metadata
languages: ["en", "de"]
countryFlags:
  en: us
  de: de
# exclude_from_localizations: ["javascript", "images", "css"]
title: FTL Hyperspace
description: "A binary mod for FTL: Faster Than Light"
show_downloads: false
baseurl: /FTL-Hyperspace
