set(CMAKE_SYSTEM_NAME Linux)

set(CMAKE_C_COMPILER /usr/bin/clang-10 CACHE PATH "")
set(CMAKE_CXX_COMPILER /usr/bin/clang++-10 CACHE PATH "")
set(CMAKE_C_FLAGS_INIT "--gcc-toolchain=/usr/gcc-4.8-clang-toolchain/ -D_GLIBCXX_USE_CXX11_ABI=0 -m32")
set(CMAKE_CXX_FLAGS_INIT "--gcc-toolchain=/usr/gcc-4.8-clang-toolchain/ -D_GLIBCXX_USE_CXX11_ABI=0 -m32")
set(CMAKE_C_FLAGS_DEBUG_INIT "-DDEBUG")
set(CMAKE_CXX_FLAGS_DEBUG_INIT "-DDEBUG")
set(CMAKE_C_FLAGS_RELEASE_INIT "-DNDEBUG")
set(CMAKE_CXX_FLAGS_RELEASE_INIT "-DNDEBUG")

# Created by Dockerfile
set(CMAKE_FIND_ROOT_PATH /usr/gcc-4.8-clang-toolchain)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

