#ifndef LUADEFINES_H_INCLUDED
#define LUADEFINES_H_INCLUDED

#include "luaInclude.h"
#include "../FTLGame.h"

/***
@table SDLKey
@remark Move to defines module
@usage
function MyCallback(key)
    if key == Defines.SDL.Keys.KEY_DELETE then
        print("Delete was pressed")
    end
end

script.on_internal_event(Defines.InternalEvents.KEY_DOWN, MyCallback)

@field UNKNOWN 0
@field 0 30
@field 1 31
@field 2 32
@field 3 33
@field 4 34
@field 5 35
@field 6 36
@field 7 37
@field 8 38
@field 9 39
@field AT 40
@field AMPERSAND 26
@field ASTERISK 2A
@field BACKQUOTE 60
@field BACKSLASH 5C
@field BACKSPACE 8
@field BREAK 13E
@field CAPSLOCK 12D
@field CARET 5E
@field CLEAR C
@field COLON 3A
@field COMMA 2C
@field COMPOSE 13A
@field DELETE 7F
@field DOLLAR 24
@field DOWN 112
@field END 117
@field EQUALS 3D
@field ESCAPE 1B
@field EURO 141
@field EXCLAIM 21
@field F1 11A
@field F10 123
@field F11 124
@field F12 125
@field F13 126
@field F14 127
@field F15 128
@field F2 11B
@field F3 11C
@field F4 11D
@field F5 11E
@field F6 11F
@field F7 120
@field F8 121
@field F9 122
@field GREATER 3E
@field HASH 24
@field HELP 13B
@field HOME 116
@field INSERT 115
@field KP0 100
@field KP1 101
@field KP2 102
@field KP3 103
@field KP4 104
@field KP5 105
@field KP6 106
@field KP7 107
@field KP8 108
@field KP9 109
@field KP_PERIOD 10A
@field KP_DIVIDE 10B
@field KP_MULTIPLY 10C
@field KP_MINUS 10D
@field KP_PLUS 10E
@field KP_ENTER 10F
@field KP_EQUALS 110
@field LALT 134
@field LCTRL 132
@field LEFT 114
@field LEFTBRACKET 5B
@field LEFTPAREN 28
@field LESS 3C
@field LMETA 136
@field LSHIFT 130
@field LSUPER 137
@field MENU 13F
@field MINUS 2D
@field MODE 139
@field NUMLOCK 12C
@field PAGEDOWN 119
@field PAGEUP 118
@field PAUSE 13
@field PERIOD 2E
@field PLUS 2B
@field POWER 140
@field PRINTSCREEN 13C
@field QUESTION 3F
@field QUOTEDBL 22
@field QUOTE 27
@field RALT 133
@field RCTRL 131
@field RETURN D
@field RIGHT 113
@field RIGHTBRACKET 5D
@field RIGHTPAREN 29
@field RMETA 135
@field RSHIFT 12F
@field RSUPER 138
@field SCROLLOCK 12E
@field SEMICOLON 3B
@field SLASH 2F
@field SPACE 20
@field SYSREQ 13D
@field TAB 9
@field UNDERSCORE 5F
@field UNDO 142
@field UP 111
@field a 61
@field b 62
@field c 63
@field d 64
@field e 65
@field f 66
@field g 67
@field h 68
@field i 69
@field j 6A
@field k 6B
@field l 6C
@field m 6D
@field n 6E
@field o 6F
@field p 70
@field q 71
@field r 72
@field s 73
@field t 74
@field u 75
@field v 76
@field w 77
@field x 78
@field y 79
@field z 7A
@field LAST 143
*/
struct SDL
{
    enum Keys
    {
        KEY_UNKNOWN = SDLK_UNKNOWN,
        KEY_0 = SDLK_0,
        KEY_1 = SDLK_1,
        KEY_2 = SDLK_2,
        KEY_3 = SDLK_3,
        KEY_4 = SDLK_4,
        KEY_5 = SDLK_5,
        KEY_6 = SDLK_6,
        KEY_7 = SDLK_7,
        KEY_8 = SDLK_8,
        KEY_9 = SDLK_9,
        KEY_AT = SDLK_AT,
        KEY_AMPERSAND = SDLK_AMPERSAND,
        KEY_ASTERISK = SDLK_ASTERISK,
        KEY_BACKQUOTE = SDLK_BACKQUOTE,
        KEY_BACKSLASH = SDLK_BACKSLASH,
        KEY_BACKSPACE = SDLK_BACKSPACE,
        KEY_BREAK = SDLK_BREAK,
        KEY_CAPSLOCK = SDLK_CAPSLOCK,
        KEY_CARET = SDLK_CARET,
        KEY_CLEAR = SDLK_CLEAR,
        KEY_COLON = SDLK_COLON,
        KEY_COMMA = SDLK_COMMA,
        KEY_COMPOSE = SDLK_COMPOSE,
        KEY_DELETE = SDLK_DELETE,
        KEY_DOLLAR = SDLK_DOLLAR,
        KEY_DOWN = SDLK_DOWN,
        KEY_END = SDLK_END,
        KEY_EQUALS = SDLK_EQUALS,
        KEY_ESCAPE = SDLK_ESCAPE,
        KEY_EURO = SDLK_EURO,
        KEY_EXCLAIM = SDLK_EXCLAIM,
        KEY_F1 = SDLK_F1,
        KEY_F10 = SDLK_F10,
        KEY_F11 = SDLK_F11,
        KEY_F12 = SDLK_F12,
        KEY_F13 = SDLK_F13,
        KEY_F14 = SDLK_F14,
        KEY_F15 = SDLK_F15,
        KEY_F2 = SDLK_F2,
        KEY_F3 = SDLK_F3,
        KEY_F4 = SDLK_F4,
        KEY_F5 = SDLK_F5,
        KEY_F6 = SDLK_F6,
        KEY_F7 = SDLK_F7,
        KEY_F8 = SDLK_F8,
        KEY_F9 = SDLK_F9,
        KEY_GREATER = SDLK_GREATER,
        KEY_HASH = SDLK_HASH,
        KEY_HELP = SDLK_HELP,
        KEY_HOME = SDLK_HOME,
        KEY_INSERT = SDLK_INSERT,
        KEY_KP0 = SDLK_KP0,
        KEY_KP1 = SDLK_KP1,
        KEY_KP2 = SDLK_KP2,
        KEY_KP3 = SDLK_KP3,
        KEY_KP4 = SDLK_KP4,
        KEY_KP5 = SDLK_KP5,
        KEY_KP6 = SDLK_KP6,
        KEY_KP7 = SDLK_KP7,
        KEY_KP8 = SDLK_KP8,
        KEY_KP9 = SDLK_KP9,
        KEY_KP_PERIOD = SDLK_KP_PERIOD,
        KEY_KP_DIVIDE = SDLK_KP_DIVIDE,
        KEY_KP_MULTIPLY = SDLK_KP_MULTIPLY,
        KEY_KP_MINUS = SDLK_KP_MINUS,
        KEY_KP_PLUS = SDLK_KP_PLUS,
        KEY_KP_ENTER = SDLK_KP_ENTER,
        KEY_KP_EQUALS = SDLK_KP_EQUALS,
        KEY_LALT = SDLK_LALT,
        KEY_LCTRL = SDLK_LCTRL,
        KEY_LEFT = SDLK_LEFT,
        KEY_LEFTBRACKET = SDLK_LEFTBRACKET,
        KEY_LEFTPAREN = SDLK_LEFTPAREN,
        KEY_LESS = SDLK_LESS,
        KEY_LMETA = SDLK_LMETA,
        KEY_LSHIFT = SDLK_LSHIFT,
        KEY_LSUPER = SDLK_LSUPER,
        KEY_MENU = SDLK_MENU,
        KEY_MINUS = SDLK_MINUS,
        KEY_MODE = SDLK_MODE,
        KEY_NUMLOCK = SDLK_NUMLOCK,
        KEY_PAGEDOWN = SDLK_PAGEDOWN,
        KEY_PAGEUP = SDLK_PAGEUP,
        KEY_PAUSE = SDLK_PAUSE,
        KEY_PERIOD = SDLK_PERIOD,
        KEY_PLUS = SDLK_PLUS,
        KEY_POWER = SDLK_POWER,
        KEY_PRINTSCREEN = SDLK_PRINTSCREEN,
        KEY_QUESTION = SDLK_QUESTION,
        KEY_QUOTEDBL = SDLK_QUOTEDBL,
        KEY_QUOTE = SDLK_QUOTE,
        KEY_RALT = SDLK_RALT,
        KEY_RCTRL = SDLK_RCTRL,
        KEY_RETURN = SDLK_RETURN,
        KEY_RIGHT = SDLK_RIGHT,
        KEY_RIGHTBRACKET = SDLK_RIGHTBRACKET,
        KEY_RIGHTPAREN = SDLK_RIGHTPAREN,
        KEY_RMETA = SDLK_RMETA,
        KEY_RSHIFT = SDLK_RSHIFT,
        KEY_RSUPER = SDLK_RSUPER,
        KEY_SCROLLOCK = SDLK_SCROLLOCK,
        KEY_SEMICOLON = SDLK_SEMICOLON,
        KEY_SLASH = SDLK_SLASH,
        KEY_SPACE = SDLK_SPACE,
        KEY_SYSREQ = SDLK_SYSREQ,
        KEY_TAB = SDLK_TAB,
        KEY_UNDERSCORE = SDLK_UNDERSCORE,
        KEY_UNDO = SDLK_UNDO,
        KEY_UP = SDLK_UP,
        KEY_a = SDLK_a,
        KEY_b = SDLK_b,
        KEY_c = SDLK_c,
        KEY_d = SDLK_d,
        KEY_e = SDLK_e,
        KEY_f = SDLK_f,
        KEY_g = SDLK_g,
        KEY_h = SDLK_h,
        KEY_i = SDLK_i,
        KEY_j = SDLK_j,
        KEY_k = SDLK_k,
        KEY_l = SDLK_l,
        KEY_m = SDLK_m,
        KEY_n = SDLK_n,
        KEY_o = SDLK_o,
        KEY_p = SDLK_p,
        KEY_q = SDLK_q,
        KEY_r = SDLK_r,
        KEY_s = SDLK_s,
        KEY_t = SDLK_t,
        KEY_u = SDLK_u,
        KEY_v = SDLK_v,
        KEY_w = SDLK_w,
        KEY_x = SDLK_x,
        KEY_y = SDLK_y,
        KEY_z = SDLK_z,
        KEY_LAST = SDLK_LAST,
    };
};

#endif // LUADEFINES_H_INCLUDED
