#ifndef PALMEMORYPROTECTION_H_INCLUDED
#define PALMEMORYPROTECTION_H_INCLUDED

#include "detours.h"

#define MEMPROT_SAVE_PROT(NAME) MOLOGIE_DETOURS_MEMORY_WINDOWS_INIT((NAME))
#define MEMPROT_UNPROTECT(ADDRESS, SIZE, OLDPROT) MOLOGIE_DETOURS_MEMORY_UNPROTECT((ADDRESS), (SIZE), (OLDPROT))
#define MEMPROT_REPROTECT(ADDRESS, SIZE, OLDPROT) MOLOGIE_DETOURS_MEMORY_REPROTECT((ADDRESS), (SIZE), (OLDPROT))

#ifdef _WIN32
    #define MEMPROT_PAGESIZE()
#else
    #include <unistd.h>
    #define MEMPROT_PAGESIZE() size_t pageSize_ = sysconf(_SC_PAGESIZE)
#endif

#endif // PALMEMORYPROTECTION_H_INCLUDED
