name: 'Build'
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: buildscripts/buildall-from-docker.sh

      - name: Store output
        uses: actions/upload-artifact@v3
        with:
          name: hyperspace-binary
          path: |
            build-*/Hyperspace.dll
            build-*/Hyperspace.*.so
